### ISSUE TITLE
rcpy_blink.py not working on 2018-5-20 image

### ISSUE THREAD

**Issue by nezra** [mcdeoliveira/rcpy#10]
Running this results in the following:

`/usr/local/lib/python3.5/dist-packages/rcpy/__init__.py:116: UserWarning: > Robotics cape initialized
  warnings.warn('> Robotics cape initialized')
/usr/local/lib/python3.5/dist-packages/rcpy/__init__.py:127: UserWarning: > Installing signal handlers
  warnings.warn('> Installing signal handlers')
Traceback (most recent call last):
  File "/var/lib/cloud9/examples/robot/python/rcpy_blink.py", line 4, in <module>
    import rcpy.gpio as gpio
  File "/usr/local/lib/python3.5/dist-packages/rcpy/gpio.py", line 4, in <module>
    import gpiod
ImportError: libgpiod.so.2: cannot open shared object file: No such file or directory
Initiating cleanup...
Done with cleanup
`
i tested several other examples and they work fine, including ADC(Thank you sooo much!)

rc_version states 0.4.4

**Comment by nezra** [comment]
closing. apparently it's conflicting with the pre-installed adafruit bbio library.
