### ISSUE TITLE
failure to initialize PWM subsystem 1

### ISSUE THREAD

**Issue by dmalawey** [mcdeoliveira/rcpy#15]
I'm running a program which drives two motors on M1 and M2 ports on beaglebone Blue. 

This program has run today multiple times, and has errored out the last two times.  No hardware changes were made. 
```

debian@beaglebone:~/SCUTTLE/software/python/basics$ sudo python3 L3_telemetry.py
/usr/local/lib/python3.7/dist-packages/rcpy-0.5.1-py3.7-linux-armv7l.egg/rcpy/__init__.py:116: UserWarning: > Robotics cape initialized
  warnings.warn('> Robotics cape initialized')
/usr/local/lib/python3.7/dist-packages/rcpy-0.5.1-py3.7-linux-armv7l.egg/rcpy/__init__.py:127: UserWarning: > Installing signal handlers
  warnings.warn('> Installing signal handlers')
WARNING: no accelerometer calibration data found
Please run rc_calibrate_accel

WARNING: no accelerometer calibration data found
Please run rc_calibrate_accel

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
DEBUG: Adafruit_BBIO: set_pin_mode() :: Pinmux file: /sys/devices/platform/ocp/ocp:P9_23_pinmux/state, mode: gpioDEBUG: Adafruit_BBIO: set_pin_mode(): beaglebone_blue() is TRUE; return BBIO_OK
DEBUG: Adafruit_BBIO: set_pin_mode() :: Pinmux file: /sys/devices/platform/ocp/ocp:P9_28_pinmux/state, mode: gpioDEBUG: Adafruit_BBIO: set_pin_mode(): beaglebone_blue() is TRUE; return BBIO_OK
ERROR in rc_pwm_init, export failed for subsystem 1 channel 0
tried accessing /sys/class/pwm/pwm-4:0/enable
ERROR in rc_motor_init, failed to initialize pwm subsystem 1
Traceback (most recent call last):
  File "L3_telemetry.py", line 21, in <module>
    import L2_speed_control as sc
  File "/home/debian/SCUTTLE/software/python/basics/L2_speed_control.py", line 8, in <module>
    import L1_motors as m                               # for controlling motors
  File "/home/debian/SCUTTLE/software/python/basics/L1_motors.py", line 7, in <module>
    import rcpy.motor as motor
  File "/usr/local/lib/python3.7/dist-packages/rcpy-0.5.1-py3.7-linux-armv7l.egg/rcpy/motor.py", line 2, in <module>
    from rcpy._motor import *
SystemError: initialization of _motor failed without raising an exception
Initiating cleanup...
Done with cleanup
debian@beaglebone:~/SCUTTLE/software/python/basics$
```

**Comment by silver2row** [comment]
Hello...how did you install the lib. on Bullseye w/ gcc-10?

Seth
